### ISSUE TITLE
CNV calling

### ISSUE THREAD

**Issue by RaphaelHablesreiter** [MissionBio/mosaic#2]
Hi,

is there a possibility to identify the diploid cells in one dataset so that this information can be use in compute_ploidy()?

Many thanks!

**Comment by eroesti** [comment]
Hi, I have a question regarding the visualization of CNVs.

I have assigned the DNA labels to the sample.cnv onbject as followed:

`sample.cnv.set_labels(filtered_dna.get_labels())`
`sample.cnv.set_palette(filtered_dna.get_palette())`

I would like to visualize the heatmap with features ordered by chromosomes and genes, however only ordering by default amplicons works:

`sample.cnv.heatmap('ploidy', features=sample.cnv.ids())`

When adjusting the command with  `features='positions'` or `features='genes'` doesnt work and result in the following error:

` Not all the given features were found in the assay ids.`

How do the labels need to be assigned in order to work? Thanks in advance!!

**Comment by arribasm** [comment]
A typical use case is to define a WT population from the dna data clustering and use this to define the diploid population.
`sample.cnv.compute_ploidy(diploid_cells=sample.dna.barcodes('WT'))`
