### ISSUE TITLE
Conda installation problem

### ISSUE THREAD

**Issue by haochenz96** [MissionBio/mosaic#5]
Hi,

Thanks for developing such a handy tool to look at Tapestri data.

I installed Mosaic about 3 weeks ago and have been using it without any problem. Today for some other reason I tried to reinstall Mosaic, and Conda was not able to (takes forever and finally times out) solve the environment while executing the command `conda install -c missionbio -c plotly -c conda-forge missionbio.mosaic`.

Any help would be appreciated!

**Comment by KKJSP** [comment]
Hello,

I was able to replicate the issue. Following is a workaround for now.

1. Delete the old environment (if it exists) `conda remove --name mosaic --all`
2. Install a specific version of mosaic `conda create --name mosaic -c missionbio -c plotly -c conda-forge missionbio.mosaic=1.7.4`

Note: Due to the various dependencies environment resolution fails for mosaic if it's done in an existing environment with other packages. Always reinstall or update in a fresh environment.

**Comment by haochenz96** [comment]
Thanks!

This solved the problem and I was able to install Mosaic.

I don't understand the difference between doing the environment creation & package installation in one line and doing them in two separate commands. I thought the latter also installs the package into an empty environment?

I didn't specify mosaic version 1.7.4 earlier, but I tried 1.6.2 which didn't work.

**Comment by KKJSP** [comment]
@haochenz96 They are the equivalent. You could have done the following as well.

```
conda remove --name mosaic --all

conda create --name mosaic --yes
conda activate mosaic
conda install -c missionbio -c plotly -c conda-forge missionbio.mosaic=1.7.4
```

Not sure why solving the environment takes significantly longer when the package version is not specified. We'll look into it and fix it.

**Comment by haochenz96** [comment]
I think that is exactly what I did. Please let me know if you can replicate
with not specifying the version.

**Comment by KKJSP** [comment]
The original command to install mosaic should now be much faster. No need to mention the version number.

`conda create --name mosaic -c missionbio -c plotly -c conda-forge missionbio.mosaic`

Since there were quite a few versions of mosaic with each having slightly different dependencies, it took a long time to solve the environment. All previous versions of mosaic have been labeled as `unsupported` (More about [anaconda labels here](https://docs.anaconda.com/anacondaorg/user-guide/tutorials/)). By default, conda will only search the packages labeled as `main` and install the latest compatible version. The previous versions can be downloaded from [here](https://anaconda.org/missionbio/missionbio.mosaic/files). It's not recommended to use those however.

Closing this issue since the latest version of mosaic can be installed as per the original method.
