### ISSUE TITLE
Slicing data doubles memory use

### ISSUE THREAD

**Issue by jil24** [MissionBio/mosaic#9]
I am having an issue with a large merged dataset which is about 40 gb in memory when initially loaded.
After identifying informative DNA variants, I attempt to slice the dataset to retain only those variants:

`Merged_Samples.dna = Merged_Samples.dna[Merged_Samples.dna.barcodes(), Merged_Samples_dna_vars]`

Memory usage more than doubles at this point, and python crashes. Is there any way to either slice in-batches and then re-concatenate, or otherwise manage the memory usage more efficiently?

**Comment by KKJSP** [comment]
@jil24 The slicing of the assay duplicates the data before subsetting it. This is done to ensure that the h5 file doesn't have to be reloaded and the filtered data can be restored using the `sample.reset()` function. There are two ways to handle this situation.

1. Load only the variants that pass the defaults minimum filters. You have to pass `apply_filter=True` to `mio.load()` to do that - [docs page](https://missionbio.github.io/mosaic/pages/functions/missionbio.mosaic.io.load.html#missionbio.mosaic.io.load). If there are any variants in particular that you are interested in, you can also pass `whitelist` to the same function to load them.
2. If you want to load all the variants, then instead of slicing the assay you can run `Merged_Samples.dna.select_columns(indices_of_variants_to_keep)`. This will subset the assay **in place** and make the `sample.reset("dna")` function obsolete.

**Comment by jil24** [comment]
Perfect! I did not think to check the mio.load() documentation.
